<!-- Documentation produced by the Html generator of Bouml (http://bouml.free.fr) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<title>Class Error</title>
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body bgcolor="#ffffff">

<div class = "title">Class Error</div>
<p></p>

<!-- ============================================================= -->

<a name="refclass135557"></a>
<p>Declaration :</p><ul><li>C++ : class Error : public <a href="class136325.html#refclass136325"><b>std::exception</b></a> </li></ul><p>Directly inherited by : <a href="class135813.html#refclass135813"><b>Config</b></a> <a href="class136197.html#refclass136197"><b>External</b></a> <a href="class136069.html#refclass136069"><b>Invalid</b></a> <a href="class135685.html#refclass135685"><b>Logic</b></a> <a href="class135941.html#refclass135941"><b>State</b></a> </p>
<p>Artifact : <a href="index.html#refartifact135813"><b>error</b></a>, Component(s) : <a href="index.html#refcomponent129925"><b>CommonLib</b></a></p><div class="sub">
<a name="refoperation131845"></a>
<table><tr><td><div class="element">Operation <b>what</b></div></td></tr></table><p>Declaration :</p><ul><li>Uml : + what() : const char*</li><li>C++ : public: virtual const char* what () const </li></ul><a name="refoperation131973"></a>
<table><tr><td><div class="element">Operation <b>rootCause</b></div></td></tr></table><p>If this exception was caused by a chain of further exceptions,<br />return the first one registered in this throw sequence.<br />This works only, if every exceptions thrown as a consequence<br />of another exception is propperly constructed by passing<br />the original exception to the constructor<br /></p><p>Declaration :</p><ul><li>Uml : + rootCause() : std::exception</li><li>C++ : public: std::exception rootCause () </li></ul><a name="refattribute130309"></a>
<table><tr><td><div class="element">Attribut <b>cause</b></div></td></tr></table>
<p>a copy of the first exception encountered in this exception chain<br /></p><p>Declaration :</p><ul><li>Uml : - cause : <a href="class136325.html#refclass136325"><b>std::exception</b></a></li><li>C++ : private: <a href="class136325.html#refclass136325"><b>std::exception</b></a> cause</li></ul><p>Stereotype: auto_ptr</p>
</div>
<p>All public operations : <a href="class135557.html#refoperation131973"><b>rootCause</b></a> , <a href="class135557.html#refoperation131845"><b>what</b></a> , <a href="class136325.html#refoperation131717"><b>what</b></a> </p>
</body>
</html>
